import { Member } from './../types';
export const members: Member[] = [
  { id: 1, name: 'John Doe', email: 'john.doe@example.com', phone: '123-456-7890', active: true },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '987-654-3210',
    active: false,
  },
  {
    id: 3,
    name: 'Michael Johnson',
    email: 'michael.johnson@example.com',
    phone: '555-123-4567',
    active: true,
  },
  {
    id: 4,
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '555-234-5678',
    active: false,
  },
  {
    id: 5,
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    phone: '555-345-6789',
    active: true,
  },
  {
    id: 6,
    name: 'Sarah Martinez',
    email: 'sarah.martinez@example.com',
    phone: '555-456-7890',
    active: true,
  },
  {
    id: 7,
    name: 'Christopher Brown',
    email: 'christopher.brown@example.com',
    phone: '555-567-8901',
    active: false,
  },
  {
    id: 8,
    name: 'Jessica Taylor',
    email: 'jessica.taylor@example.com',
    phone: '555-678-9012',
    active: true,
  },
  {
    id: 9,
    name: 'Daniel Anderson',
    email: 'daniel.anderson@example.com',
    phone: '555-789-0123',
    active: true,
  },
  {
    id: 10,
    name: 'Michelle Thomas',
    email: 'michelle.thomas@example.com',
    phone: '555-890-1234',
    active: false,
  },
  {
    id: 11,
    name: 'Ryan Jackson',
    email: 'ryan.jackson@example.com',
    phone: '555-901-2345',
    active: true,
  },
  {
    id: 12,
    name: 'Laura White',
    email: 'laura.white@example.com',
    phone: '555-012-3456',
    active: true,
  },
  {
    id: 13,
    name: 'Kevin Harris',
    email: 'kevin.harris@example.com',
    phone: '555-123-4567',
    active: false,
  },
  {
    id: 14,
    name: 'Amanda Martin',
    email: 'amanda.martin@example.com',
    phone: '555-234-5678',
    active: true,
  },
  {
    id: 15,
    name: 'James Lee',
    email: 'james.lee@example.com',
    phone: '555-345-6789',
    active: true,
  },
  {
    id: 16,
    name: 'Stephanie Clark',
    email: 'stephanie.clark@example.com',
    phone: '555-456-7890',
    active: false,
  },
  {
    id: 17,
    name: 'Brian Lewis',
    email: 'brian.lewis@example.com',
    phone: '555-567-8901',
    active: true,
  },
  {
    id: 18,
    name: 'Karen Walker',
    email: 'karen.walker@example.com',
    phone: '555-678-9012',
    active: true,
  },
  {
    id: 19,
    name: 'Matthew Hall',
    email: 'matthew.hall@example.com',
    phone: '555-789-0123',
    active: false,
  },
  {
    id: 20,
    name: 'Lisa Robinson',
    email: 'lisa.robinson@example.com',
    phone: '555-890-1234',
    active: true,
  },
  {
    id: 21,
    name: 'John Adams',
    email: 'john.adams@example.com',
    phone: '555-901-2345',
    active: true,
  },
  {
    id: 22,
    name: 'John Baker',
    email: 'john.baker@example.com',
    phone: '555-012-3456',
    active: false,
  },
  {
    id: 23,
    name: 'Olivia Murphy',
    email: 'olivia.murphy@example.com',
    phone: '555-123-4567',
    active: true,
  },
  {
    id: 24,
    name: 'John Collins',
    email: 'john.collins@example.com',
    phone: '555-234-5678',
    active: true,
  },
  {
    id: 25,
    name: 'Ava Rodriguez',
    email: 'ava.rodriguez@example.com',
    phone: '555-345-6789',
    active: false,
  },
  {
    id: 26,
    name: 'John Evans',
    email: 'john.evans@example.com',
    phone: '555-456-7890',
    active: true,
  },
  {
    id: 27,
    name: 'Sophia Garcia',
    email: 'sophia.garcia@example.com',
    phone: '555-567-8901',
    active: true,
  },
  {
    id: 28,
    name: 'John Foster',
    email: 'john.foster@example.com',
    phone: '555-678-9012',
    active: false,
  },
  {
    id: 29,
    name: 'John Harrison',
    email: 'john.harrison@example.com',
    phone: '555-789-0123',
    active: true,
  },
  {
    id: 30,
    name: 'Isabella Nelson',
    email: 'isabella.nelson@example.com',
    phone: '555-890-1234',
    active: true,
  },
];
